config/routes.rb
Rails.application.routes.draw do
  resources :invites, only: [:new, :create]
  resources :invites, path: '/', only: [:show]
  root to: 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/concerns/octoclass.rb
module Octoclass
  extend ActiveSupport::Concern

  included do
    include ActiveModel::Model
    include Comparable
  end

  def <=>(other)
    slug.downcase <=> other.slug.downcase
  end


  # use the :id for object identity
  # https://github.com/rails/rails/blob/952d0f8bdfa3f919794bf36049bafd2d95e3c97b/activerecord/lib/active_record/core.rb#L361-L386

  # Returns true if +comparison_object+ is the same exact object, or +comparison_object+
  # is of the same type and +self+ has an ID and it is equal to +comparison_object.id+.
  def ==(comparison_object)
    super ||
      comparison_object.instance_of?(self.class) &&
      !id.nil? &&
      comparison_object.id == id
  end
  alias :eql? :==

  def hash
    if id
      id.hash
    else
      super
    end
  end
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  extend FriendlyId
  friendly_id :key

  UPDATEABLE_ATTRS = %w(organization_id organization_login team_name)
  EXPIRATION = 3.days

  belongs_to :user

  validate :organization_id, presence: true
  validate :organization_login, presence: true
  validate :team_id, presence: true
  validate :team_name, presence: true
  validate :user_id, presence: true

  after_initialize :assign_key
  before_validation :update_attrs_if_needed

  def team
    Team.new(id: team_id, name: team_name, organization: organization)
  end

  def team=(team_class)
    self.organization_id = team_class.organization.id
    self.organization_login = team_class.organization.login
    self.team_id = team_class.id
    self.team_name = team_class.name
  end

  def organization
    Organization.new(id: organization_id, login: organization_login)
  end

  def add_to_team(other_user)
    user.client.add_team_member(team_id, other_user.github_username)
  end

  def expires_at
    created_at + EXPIRATION
  end

  def expired?
    Time.now > expires_at
  end

  def redeem(other_user)
    !expired? && add_to_team(other_user)
  end

  def potential_orgs_with_teams
    results = user.invitable_teams.group_by{|team| team.organization }
    results.map{|org, teams|
      OrganizationWithTeams.new(id: org.id, login: org.login, teams: teams)
    }
  end


  protected

  def assign_key
    self.key ||= SecureRandom.hex(16)
  end

  def needs_update?
    team_id &&
      team_id_changed? &&
      # update from the API if the attributes weren't set/updated as well
      (UPDATEABLE_ATTRS.any?{|a| self.send(a).nil? } ||
        (UPDATEABLE_ATTRS - changed_attributes.keys).any?
      )
  end

  def update_from_api
    self.team = Team.from_api(team_id, user.client)
  end

  def update_attrs_if_needed
    if self.needs_update?
      self.update_from_api
    end
  end
end

app/models/organization.rb
class Organization
  include Octoclass

  attr_accessor :id, :login

  def teams(client)
    client.organization_teams(login).map do |obj|
      team = Team.from_sawyer(obj)
      team.organization = self
      team
    end
  end

  def slug
    login
  end

  def url
    "https://github.com/#{login}"
  end

  def self.from_sawyer(org)
    Organization.new(id: org.id, login: org.login)
  end
end

app/models/organization_with_teams.rb
class OrganizationWithTeams < Organization
  attr_accessor :teams

  def owner?
    teams.any?(&:owners?)
  end
end

app/models/team.rb
class Team
  include Octoclass

  attr_accessor :id, :name, :organization

  def slug
    name.parameterize
  end

  def url
    "https://github.com/orgs/#{organization.login}/teams/#{slug}"
  end

  def owners?
    name == 'Owners'
  end

  def self.from_sawyer(sawyer_team)
    team = self.new(id: sawyer_team.id, name: sawyer_team.name)
    sawyer_org = sawyer_team.organization
    if sawyer_org
      team.organization = Organization.from_sawyer(sawyer_org)
    end
    team
  end

  def self.from_api(team_id, client)
    team = client.team(team_id)
    from_sawyer(team)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :invites, dependent: :destroy

  validates :github_id, presence: true
  validates :github_username, presence: true


  def client
    @client ||= Octokit::Client.new(access_token: self.token)
  end

  def organizations
    @organizations ||= client.organizations.map{|org| Organization.from_sawyer(org) }
  end

  def teams
    @teams ||= client.user_teams.map{|team| Team.from_sawyer(team) }
  end

  def invitable_teams
    results = Set.new
    teams.each do |team|
      if team.owners?
        # include all teams from that organization
        additional_teams = team.organization.teams(client)
        results.merge(additional_teams)
      else
        results << team
      end
    end
    results
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    user = self.find_or_initialize_by(github_id: auth_hash['uid'])
    # set/update fields
    user.github_username = auth_hash['info']['nickname']
    user.token = auth_hash['credentials']['token']
    user.save!

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end

  def auth_path(query={})
    "/auth/github?#{query.to_query}"
  end

  def authenticate!
    unless logged_in?
      redirect_to auth_path(origin: request.path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate!

  def show
    @invite = Invite.find_by!(key: params[:id])
    if @invite.expired?
      render 'expired', status: 410
    elsif @invite.user == current_user
      # inviter - show the page
    else
      # invite recipient
      if @invite.redeem(current_user)
        redirect_to @invite.organization.url
      else
        render 'fail', status: 503
      end
    end
  end

  def new
    @invite = Invite.new(user: current_user)
  end

  def create
    @invite = Invite.new(invite_params)
    @invite.user = current_user

    if @invite.save
      redirect_to @invite, notice: 'Invite was successfully created.'
    else
      render :new
    end
  end


  private

  def invite_params
    params.require(:invite).permit(:team_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = user
    url = request.env['omniauth.origin'] || new_invite_url
    redirect_to(url)
  end


  protected

  def auth_hash
    request.env['omniauth.auth']
  end

  # https://coderwall.com/p/bsfitw
  def current_user=(user)
    session[:user_id] = user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
  def simple_date(time)
    # http://stackoverflow.com/a/165213/358804
    time.strftime("%b #{time.day.ordinalize}")
  end
end

app/views/home/index.html.erb
<p>
  Adding large numbers of people to a GitHub organization <a href="https://help.github.com/articles/adding-organization-members-to-a-team" target="_blank">manually</a> is a hassle.  You need to collect their GitHub usernames, though they might not be signed up yet, then go through and enter them one-by-one. <strong>GitHub Invite</strong> generates a unique URL that you can send to your group, and when they click through, they will be automatically added to the team you select below.
</p>
<p class="center-block">
  <a href="<%= new_invite_path %>" class="btn btn-primary">Create invite</a>
</p>

app/views/invites/expired.html.erb
<p class="notification bg-danger">
  Sorry, this invite has expired.
  <% if @invite.user == current_user %>
    Please <a href="<%= new_invite_path %>">create a new one</a>.
  <% else %>
    Please contact an owner of the organization to request a new one.
  <% end %>
</p>

app/views/invites/fail.html.erb
<p class="notification bg-danger">
  Unable to add you to the team.  Please contact one of the Owners.
</p>

app/views/invites/new.html.erb
<p class="lead">
  Pick the team to add people to.
</p>
<hr>
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @invite.potential_orgs_with_teams.sort.each do |org| %>
    <h2>@<%= org.login %></h2>
    <ul>
      <% org.teams.each do |team| %>
        <%# exclude the Owners team %>
        <% unless team.owners? %>
          <li>
            <%= f.button class: 'btn btn-default', name: 'invite[team_id]', value: team.id do %>
              <%= team.name %>
            <% end %>
          </li>
        <% end %>
      <% end %>
      <% if org.owner? %>
        <%# has the ability to create other teams %>
        <li>
          <a href="https://github.com/orgs/<%= org.login %>/new-team" class="btn btn-default">
            <span class="glyphicon glyphicon-plus"></span>
          </a>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/invites/show.html.erb
<% if notice %>
  <p class="notification bg-success"><%= notice %></p>
<% end %>

<p class="lead">
  Share this URL with others to have them be automatically added to <a href="<%= @invite.team.url %>" target="_blank" class="mention">@<%= @invite.organization_login %>/<%= @invite.team.slug %></a>.  This link will expire in <a href="#" class="tooltipped" data-toggle="tooltip" title="<%= @invite.expires_at %>"><%= distance_of_time_in_words(Time.now, @invite.expires_at) %></a>.
</p>
<pre class="url"><%= invite_url(@invite) %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Github Invite</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-9928735-11', 'github-invite.herokuapp.com');
    ga('send', 'pageview');
  </script>
</head>
<body class="_<%= params[:action] %>">
  <div class="container">
    <h1><%= link_to "GitHub Invite", root_path %></h1>
    <%= yield %>
    <hr>
    <footer>
      <a href="https://github.com/afeld/github_invite">This site is open source</a>
    </footer>
  </div>
</body>
</html>